name: Check History Directory

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00（北京时间 08:00）
  workflow_dispatch:  # 支持手动触发

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Duplicate Check Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认 token 或自定义 PAT
        run: |
          python md/history.py

      - name: Upload Duplicate Log
        if: always()  # 即使脚本失败也上传日志
        uses: actions/upload-artifact@v4
        with:
          name: duplicate-files-log
          path: duplicate_history_files.txt
